play.http.secret.key = "VAC;>jxGR=YraHFDl8Xwdt>jGv`y^`6__c0^W5Z[Ml>7k4`]bIt/ciw/TW_wuzu>"
play.http.secret.key = ${?APPLICATION_SECRET}

play.filters.hosts {
  allowed = ["localhost", "127.0.0.1", ".localhost"]
}
